import { Task } from './types';
import { COLUMN_ID } from '@/src/shared/constants';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'API 엔드포인트 설계',
    description: 'RESTful API 설계 및 문서화 작업',
    columnId: COLUMN_ID.TODO,
    order: 1,
    priority: 'low',
    tags: ['backend', 'api'],
    assignee: '김개발',
    dueDate: new Date('2024-01-20'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'UI 컴포넌트 개발',
    description: '공통 컴포넌트 라이브러리 구축',
    columnId: COLUMN_ID.IN_PROGRESS,
    order: 1,
    priority: 'medium',
    tags: ['frontend', 'react'],
    assignee: '박프론트',
    dueDate: new Date('2024-01-25'),
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    title: '데이터베이스 스키마 설계',
    description: 'PostgreSQL 스키마 및 인덱스 최적화',
    columnId: COLUMN_ID.TODO,
    order: 2,
    priority: 'high',
    tags: ['database', 'optimization'],
    assignee: '이디비',
    dueDate: new Date('2024-01-18'),
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
  },
  {
    id: '4',
    title: '사용자 인증 구현',
    description: 'JWT 기반 인증 시스템 구축',
    columnId: COLUMN_ID.IN_PROGRESS,
    order: 2,
    priority: 'high',
    tags: ['security', 'auth'],
    assignee: '최보안',
    dueDate: new Date('2024-01-22'),
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '5',
    title: '테스트 코드 작성',
    description: '단위 테스트 및 통합 테스트 구현',
    columnId: COLUMN_ID.TODO,
    order: 3,
    priority: 'medium',
    tags: ['testing', 'quality'],
    assignee: '정테스트',
    dueDate: new Date('2024-01-30'),
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: '6',
    title: '배포 파이프라인 구축',
    description: 'CI/CD 자동화 설정',
    columnId: COLUMN_ID.DONE,
    order: 1,
    priority: 'low',
    tags: ['devops', 'ci/cd'],
    assignee: '강데브옵스',
    dueDate: new Date('2024-01-19'),
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
];

